#!/usr/bin/env bash

set -u

repo_root="$(CDPATH='' cd -- "$(dirname -- "$0")/../.." && pwd)"
# shellcheck source=tests/test-helper.sh
. "$repo_root/tests/test-helper.sh"

test_root=$(mktemp -d '/tmp/foreman-installation.XXXXXX') || exit 1
trap 'rm -rf "$test_root"' EXIT HUP INT TERM

fixture="$test_root/repository"
link_directory="$test_root/preferred-bin"
mkdir -p "$fixture/scripts" "$fixture/src"
cp "$repo_root/scripts/install.sh" "$fixture/scripts/install.sh"
cp "$repo_root/src/main.sh" "$fixture/src/main.sh"
cp "$repo_root/src/cli.sh" "$fixture/src/cli.sh"
cp "$repo_root/src/version.sh" "$fixture/src/version.sh"

test_repository_launcher_is_generated_and_replaceable() {
  local output

  output=$(bash "$fixture/scripts/install.sh") ||
    test_fail 'repository launcher installation failed'
  test_assert_contains "$output" 'Installed repository launcher:' \
    'installer did not report the generated launcher'
  [ -x "$fixture/foreman" ] || test_fail 'generated launcher is not executable'
  grep -Fqx '# Generated by scripts/install.sh. Do not edit.' "$fixture/foreman" ||
    test_fail 'generated launcher does not identify its owner'

  output=$("$fixture/foreman" version) || test_fail 'generated launcher failed'
  test_assert_equal "$output" 'foreman 0.1.0-dev' \
    'generated launcher did not reach the Foreman entry point'

  bash "$fixture/scripts/install.sh" >/dev/null ||
    test_fail 'installer could not safely refresh its own launcher'
  test_pass 'repository launcher is generated and safely replaceable'
}

test_optional_link_uses_the_same_launcher() {
  local output

  output=$(bash "$fixture/scripts/install.sh" --link "$link_directory") ||
    test_fail 'linked installation failed'
  [ -L "$link_directory/foreman" ] || test_fail 'preferred-bin link was not created'
  output=$("$link_directory/foreman" version) ||
    test_fail 'preferred-bin link could not run Foreman'
  test_assert_equal "$output" 'foreman 0.1.0-dev' \
    'preferred-bin link did not reach the Foreman entry point'
  test_pass 'optional preferred-bin link uses the repository launcher'
}

test_foreign_launcher_is_preserved() {
  local output status

  printf '#!/usr/bin/env bash\nprintf "foreign\\n"\n' >"$fixture/foreman"
  chmod 0755 "$fixture/foreman"

  set +e
  output=$(bash "$fixture/scripts/install.sh" 2>&1)
  status=$?
  set -e

  [ "$status" -ne 0 ] || test_fail 'installer replaced an unowned launcher'
  test_assert_contains "$output" 'refusing to replace launcher not owned' \
    'installer refusal did not explain launcher ownership'
  test_assert_equal "$("$fixture/foreman")" 'foreign' \
    'installer changed the unowned launcher'
  test_pass 'foreign launcher is preserved'
}

test_repository_launcher_is_generated_and_replaceable
test_optional_link_uses_the_same_launcher
test_foreign_launcher_is_preserved
