#!/usr/bin/env bash

set -eu

repo_root="$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)"
launcher="$repo_root/foreman"
marker='# Generated by scripts/install.sh. Do not edit.'
link_directory=''
temporary=''

usage() {
  cat <<'EOF'
Usage: ./scripts/install.sh [--link ABSOLUTE_DIRECTORY]

Generate the repository-local ./foreman launcher.

Options:
  --link ABSOLUTE_DIRECTORY  Also create ABSOLUTE_DIRECTORY/foreman as a link.
  --help                     Show this help.
EOF
}

fail() {
  printf 'install failed: %s\n' "$*" >&2
  exit 1
}

cleanup() {
  if [ -n "$temporary" ] && [ -f "$temporary" ]; then
    rm -f -- "$temporary"
  fi
}

trap cleanup EXIT HUP INT TERM

while [ "$#" -gt 0 ]; do
  case "$1" in
    --link)
      [ "$#" -ge 2 ] || fail '--link requires an absolute directory'
      link_directory=$2
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      fail "unknown option: $1"
      ;;
  esac
done

if [ -n "$link_directory" ]; then
  case "$link_directory" in
    /*) ;;
    *) fail '--link requires an absolute directory' ;;
  esac

  if [ -e "$link_directory" ] && [ ! -d "$link_directory" ]; then
    fail "link destination is not a directory: $link_directory"
  fi

  link_path="$link_directory/foreman"
  if [ -e "$link_path" ] || [ -L "$link_path" ]; then
    if [ -L "$link_path" ] && [ "$(readlink "$link_path")" = "$launcher" ]; then
      :
    else
      fail "refusing to replace existing link destination: $link_path"
    fi
  fi
fi

if [ -e "$launcher" ] || [ -L "$launcher" ]; then
  if [ -L "$launcher" ] || [ ! -f "$launcher" ]; then
    fail "refusing to replace non-file launcher: $launcher"
  fi
  grep -Fqx "$marker" "$launcher" ||
    fail "refusing to replace launcher not owned by this installer: $launcher"
fi

temporary=$(mktemp "$repo_root/.foreman-launcher.XXXXXX") ||
  fail 'could not create temporary launcher'

cat >"$temporary" <<'EOF'
#!/usr/bin/env bash
# Generated by scripts/install.sh. Do not edit.

set -eu

launcher_path=$0
while [ -L "$launcher_path" ]; do
  link_target=$(readlink "$launcher_path") || exit 1
  case "$link_target" in
    /*) launcher_path=$link_target ;;
    *) launcher_path="$(dirname -- "$launcher_path")/$link_target" ;;
  esac
done

repo_root="$(CDPATH='' cd -- "$(dirname -- "$launcher_path")" && pwd)"
exec "$repo_root/src/main.sh" "$@"
EOF

chmod 0755 "$temporary"
mv -f -- "$temporary" "$launcher"
temporary=''

printf 'Installed repository launcher: %s\n' "$launcher"

if [ -n "$link_directory" ]; then
  mkdir -p -- "$link_directory"
  link_path="$link_directory/foreman"
  if [ ! -L "$link_path" ]; then
    ln -s "$launcher" "$link_path"
  fi
  printf 'Linked executable: %s\n' "$link_path"
fi
